In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pat_data_processing import Utils
import os 

CSV_PATH = os.path.join(Utils.PROJECT_ROOT, 'data', 'CGHP Study - Questionnaires_July 22, 2024_08.16.csv')

In [2]:
df = pd.read_csv(CSV_PATH)
df.columns
descriptions = df.iloc[0,:]
SAVE = False
if SAVE:
    descriptions = descriptions.to_csv(os.path.join(Utils.PROJECT_ROOT, 'data', 'questionnaire_column_descriptions.csv'))

In [3]:
cols = list(descriptions.keys())
cols

['StartDate',
 'EndDate',
 'Status',
 'IPAddress',
 'Progress',
 'Duration (in seconds)',
 'Finished',
 'RecordedDate',
 'ResponseId',
 'RecipientLastName',
 'RecipientFirstName',
 'RecipientEmail',
 'ExternalReference',
 'LocationLatitude',
 'LocationLongitude',
 'DistributionChannel',
 'UserLanguage',
 'Q53',
 'Q55',
 'Q53.1',
 'Q56',
 'Q57',
 'Q58',
 'Q59',
 'Q60',
 'Q61',
 'Q62',
 'Q63',
 'Q64',
 'Q65',
 'Q66',
 'Q67',
 'Q68',
 'Q69',
 'Q70',
 'Q71',
 'Q72',
 'Q73',
 'Q74',
 'Q75',
 'Q76',
 'Q77',
 'Q78',
 'Q79',
 'Q80',
 'Q81',
 'Q82',
 'Q83',
 'Q84',
 'Q85',
 'Q86',
 'Q87',
 'Q88',
 'Q89',
 'Q90_1',
 'Q90_2',
 'Q90_3',
 'Q90_4',
 'Q90_5',
 'Q90_6',
 'Q90_7',
 'Q90_8',
 'Q90_9',
 'Q90_10',
 'Q90_11',
 'Q90_12',
 'Q90_13',
 'Q90_14',
 'Q90_15',
 'Q1',
 'Q2',
 'Q3',
 'Q3a',
 'Q4',
 'Q4a',
 'Q5',
 'Q5a',
 'Q6',
 'Q6a',
 'Q7',
 'Q7a',
 'Q8',
 'Q8a',
 'Q1.1',
 'Q2.1',
 'Q3.1',
 'Q4.1',
 'Q5.1',
 'Q6.1',
 'Q7.1',
 'Q8.1',
 'Q9',
 'Q10',
 'Q11',
 'Q12',
 'Q1.2',
 'Q2.2',
 'Q3.2',
 'Q4.2',
 'Q5.2',
 'Q6.2',
 'Q7.2',
 'Q8.2',
 'Q9.1',
 'Q10.1',
 'Q11.1',
 'Q12.1',
 'Q13',
 'Q14',
 'Q15',
 'Q16',
 'Q91_1',
 'Q91_2',
 'Q91_3',
 'Q91_4',
 'Q91_5',
 'Q92_1',
 'Q92_2',
 'Q92_3',
 'Q92_4',
 'Q92_5',
 'Q92_6',
 'Q92_7',
 'Q92_8',
 'Q92_9',
 'Q92_10',
 'Q92_11',
 'Q92_12',
 'Q93_1',
 'Q93_2',
 'Q93_3',
 'Q93_4',
 'Q93_5',
 'Q93_6',
 'Q93_7',
 'Q93_8',
 'Q93_9',
 'Q93_10',
 'Q93_11',
 'Q93_12']

In [4]:
Demographic_cols = cols[18:54]
print(Demographic_cols)

SWBS_cols = cols[54:69]
print(len(SWBS_cols))

RiC_cols = cols[69:83]
print(len(RiC_cols))

EDS_cols = cols[83:95]
print(len(EDS_cols))

CSE_cols = cols[95:111]
print(len(CSE_cols))

SWLS_cols = cols[111:116]
print(len(SWLS_cols))

MSPSS_cols = cols[116:128]
print(len(MSPSS_cols))

Chronic_Strains_cols = cols[128:]
print(len(Chronic_Strains_cols))

['Q55', 'Q53.1', 'Q56', 'Q57', 'Q58', 'Q59', 'Q60', 'Q61', 'Q62', 'Q63', 'Q64', 'Q65', 'Q66', 'Q67', 'Q68', 'Q69', 'Q70', 'Q71', 'Q72', 'Q73', 'Q74', 'Q75', 'Q76', 'Q77', 'Q78', 'Q79', 'Q80', 'Q81', 'Q82', 'Q83', 'Q84', 'Q85', 'Q86', 'Q87', 'Q88', 'Q89']
15
14
12
16
5
12
12

In [5]:
eds_data = df[["Q53"]+EDS_cols].drop(index=[0, 1])
eds_data = eds_data.dropna()

eds_data['Frequency'] = eds_data.iloc[:, 1:-2].sum(axis=1)
eds_chron = [0, .5, 3, 36, 104, 260] # might be 360
vals = eds_data.iloc[:, 1:-2]
eds_data["Chronicity"] = vals.map(lambda x: eds_chron[int(x)]).sum(axis=1)

vals.max()

Q1.1    4
Q2.1    5
Q3.1    5
Q4.1    5
Q5.1    5
Q6.1    5
Q7.1    5
Q8.1    4
Q9      4
Q10     3
Q11     5
dtype: object

In [6]:
pd.read_csv(os.path.join(Utils.PROJECT_ROOT, 'data', 'questionnaire_column_descriptions.csv')).iloc[:,0].values

array(['StartDate', 'EndDate', 'Status', 'IPAddress', 'Progress',
       'Duration (in seconds)', 'Finished', 'RecordedDate', 'ResponseId',
       'RecipientLastName', 'RecipientFirstName', 'RecipientEmail',
       'ExternalReference', 'LocationLatitude', 'LocationLongitude',
       'DistributionChannel', 'UserLanguage', 'Q53', 'Q55', 'Q53.1',
       'Q56', 'Q57', 'Q58', 'Q59', 'Q60', 'Q61', 'Q62', 'Q63', 'Q64',
       'Q65', 'Q66', 'Q67', 'Q68', 'Q69', 'Q70', 'Q71', 'Q72', 'Q73',
       'Q74', 'Q75', 'Q76', 'Q77', 'Q78', 'Q79', 'Q80', 'Q81', 'Q82',
       'Q83', 'Q84', 'Q85', 'Q86', 'Q87', 'Q88', 'Q89', 'Q90_1', 'Q90_2',
       'Q90_3', 'Q90_4', 'Q90_5', 'Q90_6', 'Q90_7', 'Q90_8', 'Q90_9',
       'Q90_10', 'Q90_11', 'Q90_12', 'Q90_13', 'Q90_14', 'Q90_15', 'Q1',
       'Q2', 'Q3', 'Q3a', 'Q4', 'Q4a', 'Q5', 'Q5a', 'Q6', 'Q6a', 'Q7',
       'Q7a', 'Q8', 'Q8a', 'Q1.1', 'Q2.1', 'Q3.1', 'Q4.1', 'Q5.1', 'Q6.1',
       'Q7.1', 'Q8.1', 'Q9', 'Q10', 'Q11', 'Q12', 'Q1.2', 'Q2.2', 'Q3.2',
       'Q4.2', 'Q5.2', 'Q6.2', 'Q7.2', 'Q8.2', 'Q9.1', 'Q10.1', 'Q11.1',
       'Q12.1', 'Q13', 'Q14', 'Q15', 'Q16', 'Q91_1', 'Q91_2', 'Q91_3',
       'Q91_4', 'Q91_5', 'Q92_1', 'Q92_2', 'Q92_3', 'Q92_4', 'Q92_5',
       'Q92_6', 'Q92_7', 'Q92_8', 'Q92_9', 'Q92_10', 'Q92_11', 'Q92_12',
       'Q93_1', 'Q93_2', 'Q93_3', 'Q93_4', 'Q93_5', 'Q93_6', 'Q93_7',
       'Q93_8', 'Q93_9', 'Q93_10', 'Q93_11', 'Q93_12'], dtype=object)

In [9]:
swbs_data = df[["Q53"]+Utils.SWBS_COLS].drop(index=[0, 1])
swbs_data = swbs_data.dropna()
Social_Integration = ["Q90_2", "Q90_6", "Q90_11"]
Social_Acceptance = ["Q90_3", "Q90_10", "Q90_14"]
Social_Contribution = ["Q90_4", "Q90_7", "Q90_15"]
Social_Actualization = ["Q90_5", "Q90_9", "Q90_13"]
Social_Coherence = ["Q90_1", "Q90_8", "Q90_12"]
swbs_data["Social Integration"] = swbs_data[Social_Integration].sum(axis=1)
swbs_data["Social Acceptance"] = swbs_data[Social_Acceptance].sum(axis=1)
swbs_data["Social Contribution"] = swbs_data[Social_Contribution].sum(axis=1)
swbs_data["Social Actualization"] = swbs_data[Social_Actualization].sum(axis=1)
swbs_data["Social Coherence"] = swbs_data[Social_Coherence].sum(axis=1)

swbs_data

,Q53,Q90_1,Q90_2,Q90_3,Q90_4,Q90_5,Q90_6,Q90_7,Q90_8,Q90_9,...,Q90_11,Q90_12,Q90_13,Q90_14,Q90_15,Social Integration,Social Acceptance,Social Contribution,Social Actualization,Social Coherence
23,PAT_025,3,2,3,6,5,6,2,3,2,...,7,3,2,6,2,267,316,622,522,333
24,PAT_026,5,1,4,7,4,6,1,6,2,...,5,3,3,5,1,165,445,711,423,563
25,PAT_027,4,5,3,5,2,3,5,3,3,...,4,5,4,5,2,534,335,552,234,435
26,PAT028,2,1,3,4,1,6,2,2,5,...,5,3,6,4,3,165,334,423,156,223
27,PAT_022,5,4,2,6,4,3,6,5,5,...,5,2,5,6,2,435,256,662,455,552
28,PAT_023,5,2,2,4,4,6,3,4,3,...,7,5,4,5,3,267,235,433,434,545
29,PAT_024,6,2,5,6,5,5,2,5,3,...,4,2,3,5,2,254,535,622,533,652
30,PAT_029,5,4,3,6,2,6,3,5,3,...,6,2,5,4,1,466,344,631,235,552
31,PAT_030,3,3,4,4,3,4,5,4,3,...,4,3,3,4,4,344,454,454,333,343
32,PAT031,3,3,4,5,5,4,3,3,2,...,4,4,3,5,2,344,435,532,523,334
33,PAT_032,4,1,4,6,4,6,2,4,4,...,7,3,4,6,2,167,426,622,444,443
34,PAT_033,2,5,2,5,2,2,7,3,2,...,1,5,1,5,2,521,235,572,221,235
35,PAT034,1,1,4,7,6,7,2,1,1,...,7,4,2,7,1,177,427,721,612,114
36,PAT035,5,5,4,6,3,3,2,3,2,...,4,3,5,5,2,534,455,622,325,533
37,PAT036,5,3,6,5,1,5,4,3,2,...,6,3,4,5,3,356,665,543,124,533
38,PAT037,5,4,3,5,5,5,4,5,3,...,5,5,5,5,3,455,335,543,535,555
39,PAT038,5,6,4,4,4,3,4,5,4,...,4,5,4,5,4,634,435,444,444,555
40,PAT039,5,5,3,4,3,5,3,3,3,...,4,3,4,5,3,554,325,433,334,533
41,PAT040,1,1,4,7,5,7,1,1,2,...,7,3,6,6,1,177,426,711,526,113
42,PAT041,2,2,4,6,6,4,2,2,2,...,4,3,1,6,2,244,426,622,621,223
43,PAT042,5,3,1,5,3,5,5,2,2,...,5,1,3,5,5,355,155,555,323,521
44,PAT043,3,2,5,6,3,4,3,5,3,...,7,3,5,5,3,247,555,633,335,353
45,PAT044,1,2,4,6,4,5,2,2,2,...,5,3,3,5,1,255,425,621,423,123
46,PAT045,4,2,3,7,3,5,2,4,2,...,6,4,4,5,1,256,345,721,324,444
47,PAT046,3,3,3,5,3,5,2,5,2,...,3,3,2,6,2,353,326,522,322,353
48,PAT047,5,5,5,6,3,3,1,6,6,...,2,2,6,3,1,532,563,611,366,562
49,PAT048,2,2,3,6,4,6,1,2,3,...,6,4,1,6,1,266,336,611,431,224
50,PAT049,4,5,4,5,3,4,4,4,3,...,3,3,3,5,3,543,435,543,333,443
51,PAT050,5,2,3,6,2,6,1,6,3,...,5,2,6,5,1,265,345,611,236,562
52,PAT051,6,5,3,5,4,1,2,7,3,...,1,4,4,5,2,511,365,522,434,674
53,PAT052,2,2,4,6,4,6,4,5,4,...,6,4,5,6,2,266,426,642,445,254
54,053,4,2,5,6,3,6,3,4,3,...,5,5,4,5,3,265,525,633,334,445
55,PAT054,4,1,3,6,2,5,3,3,4,...,7,3,5,4,2,157,354,632,245,433
56,PAT055,6,3,6,7,5,5,4,3,5,...,7,2,5,6,2,357,646,742,555,632
57,PAT056,2,6,2,5,1,3,3,3,3,...,3,2,5,4,2,633,254,532,135,232
58,PAT057,2,2,3,6,5,5,2,3,2,...,5,2,2,4,2,255,354,622,522,232
59,PAT058,3,2,6,7,3,3,1,1,4,...,5,7,5,6,1,235,656,711,345,317
60,PAT059,5,1,2,7,2,7,1,5,5,...,7,1,6,5,1,177,235,711,256,551
61,PAT060,4,4,3,6,4,4,3,3,3,...,4,3,4,4,1,444,344,631,434,433
62,PAT061,5,1,2,7,1,6,1,5,3,...,6,2,5,5,1,166,255,711,135,552
63,PAT062,4,2,4,7,2,4,4,4,4,...,4,4,4,4,4,244,434,744,244,444
64,PAT063,5,3,3,4,3,3,4,5,5,...,4,2,6,5,4,334,355,444,356,552
65,PAT064,4,1,4,7,1,5,2,2,4,...,6,5,5,6,1,156,426,721,145,425
66,PAT065,6,6,2,5,2,1,3,6,5,...,2,4,5,4,2,612,264,532,255,664
67,PAT066,2,1,6,7,6,7,1,1,1,...,7,5,2,7,1,177,627,711,612,215
68,PAT067,1,3,3,5,2,2,3,1,5,...,3,5,7,4,2,323,354,532,257,115
69,PAT068,7,2,5,5,3,6,5,5,3,...,6,2,3,5,3,266,525,553,333,752
70,PAT069,7,6,2,7,5,2,4,5,4,...,1,5,6,6,2,621,276,742,546,755
71,PAT070,3,1,5,4,2,4,4,3,3,...,5,2,5,5,3,145,535,443,235,332
72,PAT071,2,2,5,4,2,6,3,4,3,...,7,5,1,6,4,267,526,434,231,245
73,PAT072,2,6,2,3,5,2,4,2,3,...,2,3,1,6,5,622,256,345,531,223
74,PAT073,5,3,4,4,2,5,3,4,3,...,5,3,5,5,3,355,455,433,235,543
75,PAT074,3,1,5,6,3,5,2,2,4,...,5,4,3,5,3,155,535,623,343,324
76,PAT075,4,2,4,6,4,5,2,2,1,...,5,4,1,7,1,255,427,621,411,424
77,PAT076,1,1,3,6,5,6,3,2,1,...,5,3,3,6,2,165,316,632,513,123
78,PAT077,3,3,2,5,1,2,3,2,1,...,5,3,2,5,1,325,215,531,112,323
79,PAT078,4,1,7,6,5,7,2,5,3,...,6,2,2,7,1,176,737,621,532,452
80,PAT079,1,1,6,7,6,7,1,1,1,...,6,5,1,7,1,176,617,711,611,115
81,PAT080,3,5,5,3,5,2,6,2,2,...,2,5,2,3,4,522,543,364,522,325

In [12]:
mspss_data = df[["Q53"] + Utils.MSPSS_COLS].drop(index=[0, 1])
mspss_data = mspss_data.dropna()
mspss_data

,Q53,Q92_1,Q92_2,Q92_3,Q92_4,Q92_5,Q92_6,Q92_7,Q92_8,Q92_9,Q92_10,Q92_11,Q92_12
23,PAT_025,6,5,7,7,5,7,7,7,7,5,7,7
24,PAT_026,7,7,7,6,7,7,7,7,7,7,6,7
25,PAT_027,6,6,6,6,6,6,5,5,6,6,6,6
26,PAT028,5,5,6,3,5,7,7,3,7,7,7,7
27,PAT_022,6,7,6,5,7,4,3,2,5,6,6,5
28,PAT_023,6,6,7,5,6,7,7,6,7,6,7,6
29,PAT_024,5,5,7,5,3,7,7,6,7,3,7,7
30,PAT_029,7,7,6,3,7,6,6,4,7,7,5,6
31,PAT_030,6,6,6,6,6,6,6,6,6,6,6,6
32,PAT031,6,7,7,6,6,6,7,6,5,6,6,5
33,PAT_032,6,6,7,7,7,7,7,7,7,7,7,7
34,PAT_033,1,1,6,3,1,2,1,2,5,1,5,5
35,PAT034,7,7,7,7,7,6,6,7,7,7,7,7
36,PAT035,7,7,6,5,6,4,4,7,4,7,6,4
37,PAT036,7,7,6,5,7,7,7,4,7,7,5,7
38,PAT037,5,5,5,2,5,5,4,2,5,5,5,5
39,PAT038,5,4,4,3,5,5,5,2,5,5,6,4
40,PAT039,4,4,7,6,4,6,5,5,6,4,6,6
41,PAT040,1,1,7,6,7,7,7,6,7,1,7,7
42,PAT041,6,6,7,7,6,7,7,7,7,6,7,7
43,PAT042,3,2,7,1,1,6,5,1,6,1,5,7
44,PAT043,7,7,7,7,7,5,6,7,6,7,7,7
45,PAT044,7,7,7,7,7,7,7,7,7,7,7,6
46,PAT045,4,4,7,7,4,6,6,5,6,7,7,5
47,PAT046,7,7,6,6,7,5,6,6,5,7,6,6
48,PAT047,7,7,3,2,7,7,7,1,7,7,5,7
49,PAT048,7,7,6,7,7,6,6,7,5,6,6,5
50,PAT049,5,5,1,1,5,4,4,1,4,4,1,4
51,PAT050,5,7,7,5,7,7,7,4,7,7,7,7
52,PAT051,5,6,6,4,5,7,7,3,7,4,6,7
53,PAT052,6,6,6,6,6,6,6,6,6,6,6,6
54,053,6,6,6,5,6,6,6,6,7,6,7,5
55,PAT054,7,7,7,5,7,6,6,3,6,7,5,6
56,PAT055,5,7,3,3,7,7,7,7,7,7,4,7
57,PAT056,3,6,6,4,3,5,5,5,4,4,6,5
58,PAT057,7,7,7,7,4,6,6,5,6,7,6,6
59,PAT058,2,2,5,2,2,2,2,1,2,2,5,2
60,PAT059,7,6,6,5,7,7,7,5,7,7,6,7
61,PAT060,7,7,7,7,7,7,7,7,7,7,7,7
62,PAT061,6,6,2,2,6,7,6,2,7,6,3,7
63,PAT062,7,7,5,4,7,7,7,7,7,7,7,7
64,PAT063,5,5,3,3,5,5,5,1,6,4,3,6
65,PAT064,4,7,6,3,5,5,6,3,7,7,6,7
66,PAT065,7,7,2,2,7,6,5,1,5,7,1,5
67,PAT066,7,7,5,2,7,7,7,2,7,7,5,7
68,PAT067,7,7,3,3,7,7,7,3,7,7,4,7
69,PAT068,6,6,5,5,5,6,6,3,6,7,4,5
70,PAT069,2,2,5,3,2,5,2,4,4,2,3,2
71,PAT070,7,7,6,5,6,6,7,6,7,7,7,7
72,PAT071,6,6,6,5,6,5,5,5,6,6,5,5
73,PAT072,1,1,5,3,1,5,6,5,6,1,6,7
74,PAT073,6,6,7,6,6,7,7,7,6,6,6,6
75,PAT074,5,5,6,6,6,7,7,6,7,6,5,7
76,PAT075,7,7,7,6,7,7,6,5,7,7,6,7
77,PAT076,6,6,7,5,7,7,7,5,7,7,7,7
78,PAT077,7,7,7,5,7,7,7,5,7,7,7,7
79,PAT078,7,7,5,5,7,7,7,7,7,7,5,7
80,PAT079,6,6,7,7,6,7,7,7,6,6,7,7
81,PAT080,6,6,5,5,7,6,5,5,6,7,6,5

In [15]:
cse_data = df[["Q53"] + Utils.CSE_COLS].drop(index=[0])
cse_data = cse_data.dropna()
cse_data

,Q53,Q1.2,Q2.2,Q3.2,Q4.2,Q5.2,Q6.2,Q7.2,Q8.2,Q9.1,Q10.1,Q11.1,Q12.1,Q13,Q14,Q15,Q16
1,"{""ImportId"":""QID55_TEXT""}","{""ImportId"":""QID39""}","{""ImportId"":""QID40""}","{""ImportId"":""QID41""}","{""ImportId"":""QID42""}","{""ImportId"":""QID43""}","{""ImportId"":""QID44""}","{""ImportId"":""QID45""}","{""ImportId"":""QID46""}","{""ImportId"":""QID47""}","{""ImportId"":""QID48""}","{""ImportId"":""QID49""}","{""ImportId"":""QID50""}","{""ImportId"":""QID51""}","{""ImportId"":""QID52""}","{""ImportId"":""QID53""}","{""ImportId"":""QID54""}"
2,PAT001,6,5,4,4,6,5,6,5,5,3,5,4,7,3,5,3
3,PAT002,4,3,3,4,4,3,2,4,2,1,6,2,4,2,5,2
4,PAT003,4,4,3,2,2,6,6,4,4,6,6,5,3,4,6,3
5,PAT004,7,7,5,6,7,7,7,7,7,7,7,1,7,7,7,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,PAT076,5,6,3,3,4,4,5,3,3,5,5,1,5,3,5,2
78,PAT077,5,6,4,5,5,5,7,5,2,5,5,5,5,5,5,5
79,PAT078,7,7,6,6,6,6,6,6,6,6,6,5,6,7,6,6
80,PAT079,7,4,4,1,6,4,6,3,5,7,4,6,7,4,4,2
81,PAT080,4,3,2,1,2,2,6,2,2,4,5,1,4,2,4,1

In [21]:
ric_data = df[["Q53"] + Utils.RIC_COLS].drop(index=[0, 1])
ric_data = ric_data.dropna()
ric_data["RiC Q1 Score"] = ric_data.iloc[:, 1]
ric_data["RiC Q2 Score"] = ric_data.iloc[:, 2]
frequency = ["Q3","Q4","Q5","Q6","Q7","Q8"]
same_freq = ["Q3","Q5","Q7"]
diff_freq = ["Q4","Q6","Q8"]

quality = ["Q3a","Q4a","Q5a","Q6a","Q7a","Q8a"]
same_qual = ["Q3a","Q5a","Q7a"]
diff_qual = ["Q4a","Q6a","Q8a"]

ric_data["Frequency"] = ric_data[frequency].mean(axis=1)
ric_data["Quality"] = ric_data[quality].mean(axis=1)
ric_data["Same Race Frequency"] = ric_data[same_freq].mean(axis=1)
ric_data["Different Race Frequency"] = ric_data[diff_freq].mean(axis=1)
ric_data["Same Race Quality"] = ric_data[same_qual].mean(axis=1)
ric_data["Different Race Quality"] = ric_data[diff_qual].mean(axis=1)

TypeError: Could not convert ['887777' '446788' '555465' '223300' '885858' '556533' '646100' '654565'
 '265732' '180847' '645555' '668833' '233866' '665545' '452533' '552444'
 '884888' '856572' '565644' '768766' '660533' '647700' '556566' '551855'
 '556655' '287811' '555544' '856454' '565654' '745554' '445523' '162833'
 '385534' '254545' '140515' '555511' '538844' '681866' '658566' '785553'
 '758633' '355555' '185845' '040611' '546644' '185844' '768866' '406677'
 '060756' '465566' '381814' '665566' '757755' '463433' '441641' '352552'
 '381812' '844666' '655555' '463755' '511866' '633400' '485734' '850832'
 '546600' '771121' '544533' '556611' '548155' '858711' '666676' '856554'
 '668833' '655533' '555554' '856700' '528422'] to numeric

In [28]:
ric_data[frequency].values.astype(int).mean(axis=1)

array([7.33333333, 6.16666667, 5.        , 1.66666667, 7.        ,
       4.5       , 2.83333333, 5.16666667, 4.16666667, 4.66666667,
       5.        , 5.66666667, 4.66666667, 5.16666667, 3.66666667,
       4.        , 7.33333333, 5.5       , 5.        , 6.66666667,
       3.83333333, 4.        , 5.5       , 4.83333333, 5.33333333,
       4.5       , 4.66666667, 5.33333333, 5.16666667, 5.        ,
       3.83333333, 3.83333333, 4.66666667, 4.16666667, 2.66666667,
       3.66666667, 5.33333333, 5.83333333, 6.        , 5.5       ,
       5.33333333, 4.66666667, 5.16666667, 2.        , 4.83333333,
       5.        , 6.83333333, 5.        , 4.        , 5.33333333,
       4.16666667, 5.66666667, 6.        , 3.83333333, 3.33333333,
       3.66666667, 3.83333333, 5.66666667, 5.16666667, 5.        ,
       4.5       , 2.66666667, 5.16666667, 4.33333333, 3.5       ,
       3.16666667, 4.        , 4.        , 4.66666667, 5.        ,
       6.16666667, 5.5       , 5.66666667, 4.5       , 4.83333333,
       4.33333333, 3.83333333])